import Head from 'next/head';
import { Montserrat, Roboto } from '@next/font/google';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '500', '900'],
  variable: '--font-roboto'
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['300', '500', '900'],
  variable: '--font-montserrat'
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>Header</header>

      <main>
        <div className="Slider">Slider</div>

        <div className="Story">Story</div>

        <div className="featured-mugs">featured-mugs</div>

        <div className="more-products">more-products</div>

        <div className="coffe-mgz">coffe-mgz</div>

        <div className="life-style">life-style</div>
      </main>

      <footer></footer>
    </>
  );
}
