import Header from '@/components/head/Header';
import Slider from '@/components/slider/Slider';
import Story from '@/components/story/Story';
import Head from 'next/head';

export default function Home() {
  const handleOnClick = (event: any) => {
    const toggleMenuIcon = document.getElementById('toggleMenuIcon');
    const topMenu = document.getElementById('topMenu');

    // check on click button
    if (toggleMenuIcon?.contains(event.target)) {
      // on click in menu
      topMenu?.classList.toggle('-translate-y-96');
      topMenu?.classList.toggle('translate-y-0');
      topMenu?.classList.toggle('animate-slideDown');
      topMenu?.classList.toggle('animate-closeSlideDown');
    } else {
      // on click outside
      if (topMenu?.classList.contains('hidden') == false) {
        topMenu.classList.add('hidden');
      }
    }
  };

  return (
    <>
      <Head>
        <title>Coffee TailWind</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className="max-w-screen-2xl  desktop:text-[23px] laptop:text-base mx-auto px-8"
        onClick={handleOnClick}
      >
        <Header />

        <main>
          <div className="Slider">
            <Slider />
          </div>

          <div className="Story">
            <Story />
          </div>

          <div className="featured-mugs">featured-mugs</div>

          <div className="more-products">more-products</div>

          <div className="coffe-mgz">coffe-mgz</div>

          <div className="life-style">life-style</div>
        </main>

        <footer>footer</footer>
      </div>
    </>
  );
}
