import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  const navLink: { title: string; link: string }[] = [
    {
      title: 'home',
      link: '/home'
    },
    {
      title: 'our products',
      link: '/home/products'
    },
    {
      title: 'blog',
      link: '/home/blog'
    },
    {
      title: 'about',
      link: '/home/about'
    },
    {
      title: 'contact',
      link: '/home/contact'
    },
    {
      title: 'style guide',
      link: '/home/style_guide'
    }
  ];

  return (
    <>
      <Head>
        <title>Coffee TailWind</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-screen-2xl  xl:text-[20px] text-base mx-auto px-8 bg-slate-400">
        <header className="py-6 mx-10">
          <nav className="flex flex-row justify-between items-center">
            <div className="basis-1/6/6 font-semibold cursor-pointer">CoffeeStyle.</div>

            <ul
              className="basis-4/6 flex item-center xl:text-[20px] text-base  px-10 justify-between
              text-gray-500 font-medium">
              {navLink.map((item, index) => {
                return (
                  <li key={index} className='h-full'>
                    <Link href={item.link} className="ct-navlink">
                      {item.title.toUpperCase()}
                    </Link>
                  </li>
                );
              })}
            </ul>

            <ul className="basis-1/6 flex items-center font-nunito">
              <Link href={'/cart'} className="ct-navlink h-full align-middle flex">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                  className="w-5 h-5">
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M15.75 10.5V6a3.75 3.75 0 10-7.5 0v4.5m11.356-1.993l1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 01-1.12-1.243l1.264-12A1.125 1.125 0 015.513 7.5h12.974c.576 0 1.059.435 1.119 1.007zM8.625 10.5a.375.375 0 11-.75 0 .375.375 0 01.75 0zm7.5 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z"
                  />
                </svg>
                <span>Cart</span>
                <span className=''>10</span>
              </Link>
            </ul>
          </nav>
        </header>

        <main>
          <div className="Slider">Slider</div>

          <div className="Story">Story</div>

          <div className="featured-mugs">featured-mugs</div>

          <div className="more-products">more-products</div>

          <div className="coffe-mgz">coffe-mgz</div>

          <div className="life-style">life-style</div>
        </main>

        <footer>footer</footer>
      </div>
    </>
  );
}
